#!/bin/bash

(
RC=0
read HEADER
while read -r MACHINE STATE NVT; do
  for reqsubstr in 'active' ;do
   if [ -z "${STATE##*$reqsubstr*}" ] ;then
#      echo "String '$STATE' contain substring: '$reqsubstr'.";
      echo "INFO: check $MACHINE connection via ping:"
      ping -c 1 $MACHINE &> /dev/null && (echo "ping host=$MACHINE success (OK) "; ping -c 1 $MACHINE | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1) || echo "WARNING: ping host=$MACHINE FAILED (NOK)"
   fi
  done
done
exit $RC
) < <(grep -v '^#' ./db_hosts)
exit $?

