--- 
-
  hosts: localhost
#  hosts: all
  become: true
  vars:
      FILE: sublime_text_3_build_3211_x64.tar.bz2
      LINK_NAME: sublime_text
      SOURCE_DIR: ~/Downloads
      INSTALL_DIR: /opt
  tasks:
    -
      name: "Unarchive intellij {{FILE}} artifact to dir {{INSTALL_DIR}} on host."
      unarchive:
          dest: "{{ item.dest }}"
          src: "{{ item.src }}"
          list_files: yes
      with_items:
          - {
              dest: "{{INSTALL_DIR}}",
              src: "{{SOURCE_DIR}}/{{FILE}}"
            }
      register: archive_contents
      tags:
          cp_artifact

    -
      name: debug archive_contents
      debug: var=archive_contents
      tags:
          cp_artifact
    -
      name: debug archive_contents
      debug: 'msg="Subfolder: {{archive_contents.results[0].files[0].split("/")[0]}}"'
      tags:
          cp_artifact
 
    - 
      name: Copy file with owner and permissions
      copy:
         src: sublime_text.desktop
         dest: /usr/share/applications/sublime_text.desktop
         owner: root
         group: root
         mode: '0644'
    - 
      name: "Make soft links."
      file: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          state: link
      with_items: 
          - {
              src: "{{INSTALL_DIR}}/{{ archive_contents.results[0].files[0].split('/')[0] }}/sublime_text",
              dest: "/usr/local/bin/{{LINK_NAME}}"
            }


