--- 
-
  hosts: localhost
#  hosts: all
  become: true
  vars:
      JAVA_FILE: jdk-8u271-linux-x64.tar.gz
      LINK_NAME: java-8-sun
      SOURCE_DIR: ~/Downloads
      JAVA_INSTALLS_DIR: /usr/lib/jvm
  tasks:
    -
      name: "Make java install dirs."
      file:
          path: "{{JAVA_INSTALLS_DIR}}"
          owner: root
          group: root
          state: directory
      tags:
          mk_dir
    -
      name: "Unarchive java {{JAVA_FILE}} artifact to dir {{JAVA_INSTALLS_DIR}} on host."
      unarchive:
          dest: "{{ item.dest }}"
          src: "{{ item.src }}"
          list_files: yes
      with_items:
          - {
              dest: "{{JAVA_INSTALLS_DIR}}",
              src: "{{SOURCE_DIR}}/{{JAVA_FILE}}"
            }
      register: archive_contents
      tags:
          cp_artifact

    -
      name: debug archive_contents
      debug: var=archive_contents
      tags:
          cp_artifact
    -
      name: debug archive_contents
      debug: 'msg="Subfolder: {{archive_contents.results[0].files[0]}}"'
      tags:
          cp_artifact
 
    -
      name: "fix java random on host."
      replace:
          dest: "{{JAVA_INSTALLS_DIR}}/{{ archive_contents.results[0].files[0] }}jre/lib/security/java.security"      
          regexp: '^securerandom.source=file:/dev/random'
          replace: 'securerandom.source=file:/dev/./urandom' 
      tags:
         fix_random
    -
      name: "fix java urandom on host."
      replace:
          dest: "{{JAVA_INSTALLS_DIR}}/{{ archive_contents.results[0].files[0] }}jre/lib/security/java.security"
          regexp: '^securerandom.source=file:/dev/./random'
          replace: 'securerandom.source=file:/dev/./urandom'
      tags:
         fix_random
    - 
      name: "Make soft links."
      file: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          state: link
      with_items: 
          - {
              src: "{{ archive_contents.results[0].files[0] }}",
              dest: "{{JAVA_INSTALLS_DIR}}/{{LINK_NAME}}"
            }
          - {
              src: "{{ archive_contents.results[0].files[0] }}",
              dest: "{{JAVA_INSTALLS_DIR}}/java"
            }

      tags:
         make_links

