--- 
-
  hosts: localhost
#  hosts: all
  become: true
  vars:
      FILE: ideaIC-2020.2.3.tar.gz
      LINK_NAME: intellij
      SOURCE_DIR: ~/Downloads
      INSTALL_DIR: /opt
  tasks:
    -
      name: "Unarchive intellij {{FILE}} artifact to dir {{INSTALL_DIR}} on host."
      unarchive:
          dest: "{{ item.dest }}"
          src: "{{ item.src }}"
          list_files: yes
      with_items:
          - {
              dest: "{{INSTALL_DIR}}",
              src: "{{SOURCE_DIR}}/{{FILE}}"
            }
      register: archive_contents
      tags:
          cp_artifact

    -
      name: debug archive_contents
      debug: var=archive_contents
      tags:
          cp_artifact
    -
      name: debug archive_contents
      debug: 'msg="Subfolder: {{archive_contents.results[0].files[0].split("/")[0]}}"'
      tags:
          cp_artifact
 
    - 
      name: "Make soft links."
      file: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          state: link
      with_items: 
          - {
              src: "{{ archive_contents.results[0].files[0].split('/')[0] }}",
              dest: "{{INSTALL_DIR}}/{{LINK_NAME}}"
            }

      tags:
         make_links

