#!/bin/bash

min_gb=100;
min_mb=1;
min_perc=85;
MTMPFILE="/tmp/filesystem"
#df -k | grep -v proc | grep -v Filesystem | grep -v mapper | grep -v tmpfs | grep -v sda1 | grep -v : | grep -v '^/dev/loop' | sed -f scripts/concat_space > $MTMPFILE
df -k | grep [0-9]% | sed -f scripts/concat_space > $MTMPFILE
cat $MTMPFILE | while read line
do
#   echo "line=$line"
   size_perc=$(echo $line | grep -o [0-9]*%)
   size=$(echo $size_perc | sed s/%//g)
   filet=$(echo $line | tr ' ' '\n' | tail -1)
   available_size=$(echo $line | awk  '{print $(NF-2)}' )
   available_size_mb=$((available_size/1024))
   available_size_gb=$((available_size/1024/1024))
   #first condition: little mb available
   if [ $available_size_mb -le $min_mb ]
   then
      echo "WARNING: filesystem $filet filled at $size_perc available=$available_size ($available_size_gb GB|$available_size_mb MB)"
   fi
   #second condition: high percentage usage
   if [ $size -ge $min_perc ]
   then
      if [ $available_size_gb -le $min_gb ]
      then
      echo "WARNING: filesystem $filet filled at $size_perc available=$available_size ($available_size_gb GB|$available_size_mb MB)"
      else
      echo "INFO: filesystem $filet filled at $size_perc but sufficient (min=$min_gb GB) available=$available_size ($available_size_gb GB|$available_size_mb MB)"
      fi
   fi
done
rm $MTMPFILE
