#!/bin/ksh

Exit_fail() {
   echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   echo "`date` - login log for $Pdatabase - Ending Failed"
   echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   exit -1
}

Usage() {
        echo -e "\nUsage : $0 -d <database name>\n"
        Exit_fail
}

Analyze_options_passed() {
[ -z "$Pdatabase" ] && echo -e "\nNo Database Specified..." &&  Usage
}

Execute_environment_file() {
  export ORACLE_SID=${Pdatabase}
}

login_log() {
sqlplus -s /nolog 1>> /tmp/login_log.log <<EOS
connect / as sysdba
set linesize 132;
set feedback off;
set serverout on;
set pagesize 999;
set linesize 132;
column user_id format a15;
column osuser format a15;
column host format a15;
column last_program format a20;
select user_id, osuser, host, last_program, 
       to_char(logon_day,'DD-MON-YY HH:MI:SS'), 
       to_char(logoff_day,'DD-MON-YY HH:MI:SS')
 from login_log order by logon_day;
EOS
}

Send_Mail() {
  DESTINATION=
  #cat /tmp/login_log.log | mailx -s "login on database ${Pdatabase}" "${DESTINATION}"
}

Set_environment() {

# set environment
# ---------------

WORKSID=$Pdatabase
WORKHOM=$ORACLE_HOME
 
}

main() {
echo -e "\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "`date` - $0 - Starting for $Pdatabase"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

Analyze_options_passed

Execute_environment_file

Set_environment

cat /dev/null > /tmp/login_log.log

#check databases 
login_log $dbname 

Send_Mail

echo -e "\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "`date` - $0 - Ending for $Pdatabase"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
}

while getopts "d:" opt
do
  case $opt in
        d)      Pdatabase=$OPTARG ;;
        *)      Usage
                Exit_fail
                ;;
  esac
done

main
exit 0

