--- 
-
  hosts: localhost
#  hosts: all
  become: true
  vars:
      FILE: eclipse-jee-2020-06-R-linux-gtk-x86_64.tar.gz
      LINK_NAME: eclipse
      SOURCE_DIR: ~/Downloads
      INSTALL_DIR: /opt
  tasks:
    -
      name: "Unarchive intellij {{FILE}} artifact to dir {{INSTALL_DIR}} on host."
      unarchive:
          dest: "{{ item.dest }}"
          src: "{{ item.src }}"
          list_files: yes
      with_items:
          - {
              dest: "{{INSTALL_DIR}}",
              src: "{{SOURCE_DIR}}/{{FILE}}"
            }
      register: archive_contents
      tags:
          cp_artifact

    -
      name: debug archive_contents
      debug: var=archive_contents
      tags:
          cp_artifact
    -
      name: debug archive_contents
      debug: 'msg="Subfolder: {{archive_contents.results[0].files[0].split("/")[0]}}"'
      tags:
          cp_artifact
 
    - 
      name: Copy file with owner and permissions
      copy:
         src: Eclipse.desktop
         dest: "/home/{{USER}}/.local/share/applications/Eclipse.desktop"
         owner: "{{USER}}"
         group: "{{USER}}"
         mode: '0755'


