--- 
- 
  hosts: postgres-hosts
  become: true
  gather_facts: yes
  tasks: 
    - name: "Populate service facts"
      service_facts:
    - name: "See the service facts"
      debug: 
           msg: "{{ ansible_facts.services }}"

