--- 
- 
  hosts: postgres-hosts
  become: true
  tasks: 
    -
      name: "Change  in configuration files max_connections."
      lineinfile:
          dest: /var/lib/pgsql/12/data/postgresql.conf
          regexp: '^max_connections\s*='
          line:   "max_connections = 803"
          backup: yes
      register: config1  
    -
      name: "Change  in configuration files max_prepared_transactions."
      lineinfile:
          dest: /var/lib/pgsql/12/data/postgresql.conf
          regexp: '^max_prepared_transactions\s*='
          line:   "max_prepared_transactions = 803"
          backup: yes
      register: config2
    -
      name: "Change in configuration files logfile name."
      lineinfile:
          dest: /var/lib/pgsql/12/data/postgresql.conf
          regexp: '^log_filename\s*='
          line:   "log_filename = 'postgresql-%Y-%m-%d.log'     # log file name pattern,"
          backup: yes
      register: config3
      tags: logconf
    -
      name: "Restart postgresql."
      service:
          name: sudo systemctl stop postgresql-12
          state: restarted
 #     when: (config1.changed) or (config2.changed) or (config3.changed) 
      tags: restart
